### ISSUE TITLE
Recent changes made to the font/text

### ISSUE THREAD

**Issue by GTANAdam** [aligo/better-google#11]
Google has pushed an experimental change affecting a select number of users and today, I have noticed the change.
It seems that the change only affects those Logged in, so after clearing cookies, the changes were reverted.

There's a reddit page where people had already complained about this: https://www.reddit.com/r/chrome/comments/hfa1a5/google_search_results_font_changed/

So, the changes introduced are the added "letter-spacing" which is annoying if you read Cyrillic or if you fancy well printed text.
I have compiled a list of classes which this change has affected:

```
.aCOpRe
.di3YZe 
.cbphWd
.brs_col
.HiHjCd
.Ss2Faf
.ILfuVd
.s
#res h3, #botstuff h3
```

In order to revert the change made, a simple rule insertion unsetting the letter-spacing property will fix that.

for example:
`style.sheet.insertRule('.cbphWd { letter-spacing: unset !important; }');`

I will have a Pull Request following up once I find enough time for that.

Here's a quick look at the difference
letter-spacing: 0.5
![chrome_tk7arqddlC](https://user-images.githubusercontent.com/25143912/107114614-d8a0af80-686f-11eb-9df4-221838aa0be6.png)

letter-spacing: unset or normal
![chrome_AjEzEvJAHN](https://user-images.githubusercontent.com/25143912/107114619-e0605400-686f-11eb-9462-6116458dfdca.png)

letter-spacing: 0.5
![chrome_elavY1KEAx](https://user-images.githubusercontent.com/25143912/107114695-8d3ad100-6870-11eb-9879-4d4a73b89c7b.png)

letter-spacing: unset or normal
![chrome_bsC54x327D](https://user-images.githubusercontent.com/25143912/107114687-77c5a700-6870-11eb-921a-47d8c687e496.png)

**Comment by idgas01** [comment]
Good luck trying to get @aligo to do anything.  His userscript broke on Jan 15.  It's now five weeks later, and he still hasn't updated his script.  Even though someone else did all the work for him already and all he has to do is take two seconds to approve the pull request.  Strange how he hasn't searched for anything on Google once in these five weeks.  What was the point of him in making a Better Google userscript if he never uses Google?  What a weird feller.  I mean, I would imagine that most people search for something on Google at least once a day.  If not, then definitely once a week.  He did the same thing the last time his userscript broke.  Took him one or two months to update it last time too.  Bet you anything that the script still won't be updated in March.  We probably won't see that 2 kb update till April.  I wish that the other people on his GitHub were more honest about the situation instead of white knighting him to death.  Is there a single person left in this world that was born after 1965 and has a backbone?  I'm always dealing with these virtue signaling "boo hoo" Liberal social justice warrior types.  Wish that there were more "real" people in the world, instead of these pink hat wearing sissies that do nothing but lecture you about morality.  It's like everyone is competing to be a first grade teacher who writes things on posters like "Golden Rule: Treat others the way you want to be treated."  And then they stick their nose up in the air and look down at everyone, because they think that because they know these "golden rules" that somehow they are morally superior to everyone else.  Okay, done ranting.  Just hate how I'm always right.  I said a couple of weeks ago, that he abandoned the userscript and everyone acted like "no, don't say that or he will really abandon it".  Well if two times the userscript breaks, and both times it takes him two months to update it, it's not completely abandoned but it sure in hell is 98% abandoned.  It's so irresponsible.  If you did ONE SINGLE SEARCH on Google in the last five weeks, you would know the userscript is broken and it takes TWO SECONDS to approve the pending pull request.  Guess we aren't worth two seconds.

**Comment by GTANAdam** [comment]
> Good luck trying to get @aligo to do anything. His userscript broke on Jan 15. It's now five weeks later, and he still hasn't updated his script. Even though someone else did all the work for him already and all he has to do is take two seconds to approve the pull request. Strange how he hasn't searched for anything on Google once in these five weeks. What was the point of him in making a Better Google userscript if he never uses Google? What a weird feller. I mean, I would imagine that most people search for something on Google at least once a day. If not, then definitely once a week. He did the same thing the last time his userscript broke. Took him one or two months to update it last time too. Bet you anything that the script still won't be updated in March. We probably won't see that 2 kb update till April. I wish that the other people on his GitHub were more honest about the situation instead of white knighting him to death. Is there a single person left in this world that was born after 1965 and has a backbone? I'm always dealing with these virtue signaling "boo hoo" Liberal social justice warrior types. Wish that there were more "real" people in the world, instead of these pink hat wearing sissies that do nothing but lecture you about morality. It's like everyone is competing to be a first grade teacher who writes things on posters like "Golden Rule: Treat others the way you want to be treated." And then they stick their nose up in the air and look down at everyone, because they think that because they know these "golden rules" that somehow they are morally superior to everyone else. Okay, done ranting. Just hate how I'm always right. I said a couple of weeks ago, that he abandoned the userscript and everyone acted like "no, don't say that or he will really abandon it". Well if two times the userscript breaks, and both times it takes him two months to update it, it's not completely abandoned but it sure in hell is 98% abandoned. It's so irresponsible. If you did ONE SINGLE SEARCH on Google in the last five weeks, you would know the userscript is broken and it takes TWO SECONDS to approve the pending pull request. Guess we aren't worth two seconds.

It's okay, there will certainly be a fork that takes care of the project!
