### ISSUE TITLE
script stopped working over the past couple days

### ISSUE THREAD

**Issue by swinokur** [aligo/better-google#2]
Hi,
On a very old version of firefox, 52.8.1 - the script has stopped working. Trying to debug it, I see:

"Execution of script 'Better Google' failed! Not enough arguments to CSSStyleSheet.insertRule."
![image](https://user-images.githubusercontent.com/5185651/81887945-24c6f980-9555-11ea-9357-4ef7b7c686b1.png)

Let me know if there's other information I can provide.

thanks!

**Comment by wtfiwinomgs** [comment]
i can confirm this, please update! cant browse search without this script!

**Comment by drwonky** [comment]
Google changed the "r" class to "yuRUbf" in the result heading.

By changing references to ".r" in the script to ".yuRUbf" it fixes the layout.

Attached is the fixed script (renamed to .txt because Github has limitations on filename extensions as attachments).

[better_google.txt](https://github.com/aligo/better-google/files/5309538/better_google.txt)
